<?php return array(
    5 =>
    array(
    'super_admin' => '1',
    'permissions' =>
    array(
        'view' => '1',
        'edit' => '1',
    ),
    'view' =>
    array(
        'staff' => '1',
        'update' => '1',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'messages' => '1',
        'notes' => '1',
        'curplayer' => '1',
        'logs' => '1',
        'phone' => '1',
        'wanted' => '1',
        'notes' => '1',
        'inventory' => '1',
        'gamesrv' => '1',
        'gamesrvAdmin' => '1',
    ),
    'edit' =>
    array(
        'staff' => '1',
        'update' => '1',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'inventory' => '1',
        'server' => '1',
        'notes' => '1',
        'ranks' => '1',
        'bank' => '1',
        'ignLVL' => '1',
    ),
    ),
    4 =>
    array(
    'super_admin' => '0',
    'permissions' =>
    array(
        'view' => '0',
        'grant' => '0',
    ),
    'view' =>
    array(
        'staff' => '1',
        'update' => '1',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'messages' => '1',
        'notes' => '1',
        'curplayer' => '1',
        'logs' => '0',
        'phone' => '1',
        'wanted' => '1',
        'inventory' => '1',
        'gamesrv' => '1',
        'gamesrvAdmin' => '1',
    ),
    'edit' =>
    array(
        'staff' => '1',
        'update' => '1',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'inventory' => '1',
        'server' => '0',
        'notes' => '1',
        'ranks' => '1',
        'bank' => '1',
        'ignLVL' => '1',
    ),
    ),
    3 =>
    array(
    'super_admin' => '0',
    'permissions' =>
    array(
        'view' => '0',
        'grant' => '0',
    ),
    'view' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'messages' => '1',
        'notes' => '1',
        'curplayer' => '1',
        'logs' => '0',
        'phone' => '1',
        'wanted' => '1',
        'inventory' => '1',
        'gamesrv' => '1',
        'gamesrvAdmin' => '0',
    ),
    'edit' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '1',
        'player' => '1',
        'licences' => '1',
        'inventory' => '1',
        'server' => '0',
        'notes' => '1',
        'ranks' => '1',
        'bank' => '1',
        'ignLVL' => '0',
    ),
    ),
    2 =>
    array(
    'super_admin' => '0',
    'permissions' =>
    array(
        'view' => '0',
        'grant' => '0',
    ),
    'view' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '1',
        'houses' => '1',
        'gangs' => '1',
        'wanted' => '1',
        'steam' => '0',
        'player' => '1',
        'licences' => '1',
        'messages' => '1',
        'notes' => '0',
        'curplayer' => '0',
        'logs' => '0',
        'phone' => '0',
        'inventory' => '1',
        'gamesrv' => '0',
        'gamesrvAdmin' => '0',
    ),
    'edit' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '0',
        'houses' => '0',
        'gangs' => '0',
        'wanted' => '0',
        'steam' => '0',
        'player' => '0',
        'licences' => '0',
        'inventory' => '0',
        'server' => '0',
        'notes' => '0',
        'ranks' => '0',
        'bank' => '0',
        'ignLVL' => '0',
    ),
    ),
    1 =>
    array(
    'super_admin' => '0',
    'permissions' =>
    array(
        'view' => '0',
        'grant' => '0',
    ),
    'view' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '0',
        'houses' => '0',
        'gangs' => '0',
        'wanted' => '0',
        'steam' => '0',
        'player' => '0',
        'licences' => '0',
        'messages' => '0',
        'notes' => '0',
        'curplayer' => '0',
        'logs' => '0',
        'phone' => '0',
        'inventory' => '0',
        'gamesrv' => '0',
        'gamesrvAdmin' => '0',
    ),
    'edit' =>
    array(
        'staff' => '0',
        'update' => '0',
        'vehicles' => '0',
        'houses' => '0',
        'gangs' => '0',
        'wanted' => '0',
        'steam' => '0',
        'player' => '0',
        'licences' => '0',
        'inventory' => '0',
        'server' => '0',
        'notes' => '0',
        'ranks' => '0',
        'bank' => '0',
        'ignLVL' => '0',
    ),
    ),
);